---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal
options:
  package_manager_path: /usr/bin/microdnf

dependencies:
  python_interpreter:
    package_system: python3.11
    python_path: /usr/bin/python3.11
  ansible_core:
    package_pip: ansible-core~=2.15.0
  ansible_runner:
    package_pip: ansible-runner~=2.3.0
  system: bindep.txt
  python: requirements.txt
  galaxy: requirements.yml

additional_build_files:
  - src: ansible.cfg
    dest: ./
